variables:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
  NPM_TOKEN: ${CI_JOB_TOKEN}

stages:
  - lint
  - release

code-check:
  image: node:24-alpine
  tags:
    - docker
  stage: lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_BRANCH == "refactor/dev-203")
      when: manual
    - when: never
  script:
    - apk add --no-cache git
    - corepack enable
    - corepack prepare pnpm@latest --activate
    - pnpm i
    - pnpm lint
  allow_failure: true


publish-npm:
  image: node:24-alpine
  tags:
    - docker
  stage: release
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_BRANCH == "refactor/dev-203")
      when: always
    - when: never
  script:
    - apk add --no-cache curl jq
    - corepack enable
    - corepack prepare pnpm@latest --activate
    - pnpm i
    - pnpm build
    - pnpm config set @integrity:registry ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/ 
    - pnpm config set -- //${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken ${CI_JOB_TOKEN}
    - pnpm config set @internal:registry ${CI_API_V4_URL}/packages/npm/
    - pnpm config set @labeling:registry ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/
    - pnpm config set @labeling:registry ${CI_API_V4_URL}/projects/119/packages/npm/
    - pnpm config set -- //${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken ${CI_JOB_TOKEN}
    - pnpm config set -- //${CI_SERVER_HOST}/api/v4/projects/119/packages/npm/:_authToken ${CI_JOB_TOKEN}
    - pnpm config set -- //${CI_SERVER_HOST}/api/v4/packages/npm/:_authToken ${CI_JOB_TOKEN}
    - |
      echo "📦 Получение списка пакетов..."
      curl -sS --header "PRIVATE-TOKEN:${API_GITLAB_TOKEN}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages"
    - echo "API_GITLAB_TOKEN=${API_GITLAB_TOKEN}"
    - echo "CI_API_V4_URL=${CI_API_V4_URL}"
    - echo "CI_PROJECT_ID=${CI_PROJECT_ID}"
    - |
      echo "🔍 Удаление всех пакетов..."
      curl -sS --header "PRIVATE-TOKEN:${API_GITLAB_TOKEN}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages" \
      | jq -r '.[].id' \
      | xargs -r -I{} curl -sS --request DELETE \
          --header "PRIVATE-TOKEN:${API_GITLAB_TOKEN}" \
          "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/{}" || true
    - pnpm publish -r --no-git-checks --verbose 
