packages:
  - packages/**
catalog:
  # vue
  "vue": "^3.5.16"
  "vue-i18n": "^11.1.5"
  "vue-router": "^4.5.1"
  "vue3-apexcharts": "^1.8.0"
  "pinia": "^3.0.3"
  # quasar
  "quasar": "^2.18.1"
  "@quasar/extras": "^1.17.0"
  "@quasar/vite-plugin": "^1.9.0"
  # storybook
  "storybook": "9.1.2"
  "@storybook/vue3-vite": "^9.1.2"
  "@storybook/test": "^8.6.14"
  "@storybook/addon-docs": "^9.1.2"
  "@storybook/addon-vitest": "^9.1.2"
  "@storybook/addon-a11y": "^9.1.2"
  "@chromatic-com/storybook": "^4.0.0"
  # vite
  "vite": "^6.3.5"
  "vite-plugin-dts": "^4.5.4"
  "@vitejs/plugin-vue": "^5.2.4"
  "@vitest/browser": "^3.2.2"
  "@vitest/coverage-v8": "^3.2.2"
  "@pivanov/vite-plugin-svg-sprite": "^3.0.0"
  # others
  "@bufbuild/protobuf": "^2.4.0"
  "playwright": "^1.52.0"
  "sass-embedded": "^1.89.1"
  "uuid": "^11.1.0"
  "apexcharts": "^4.7.0"
onlyBuiltDependencies:
  - '@biomejs/biome'
