// @generated by protoc-gen-es v1.10.0 with parameter "target=js"
// @generated from file labeling/api/v1/Job.proto (package labeling.api.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3, Timestamp } from '@bufbuild/protobuf'

/**
 * @generated from message labeling.api.v1.JobModel
 */
export const JobModel = /*@__PURE__*/ proto3.makeMessageType('labeling.api.v1.JobModel', () => [
  { no: 1, name: 'uuid', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
  { no: 2, name: 'ext_id', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
  { no: 3, name: 'title', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
  { no: 4, name: 'total', kind: 'scalar', T: 13 /* ScalarType.UINT32 */ },
  { no: 5, name: 'sku', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
  { no: 6, name: 'parent', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
  { no: 7, name: 'status', kind: 'enum', T: proto3.getEnumType(JobModel_JobStatus) },
  { no: 8, name: 'types', kind: 'scalar', T: 9 /* ScalarType.STRING */, repeated: true },
  { no: 9, name: 'created_by', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
  { no: 10, name: 'updated_by', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
  { no: 11, name: 'created_at', kind: 'message', T: Timestamp },
  { no: 12, name: 'updated_at', kind: 'message', T: Timestamp },
  { no: 13, name: 'attributes', kind: 'message', T: JobModel_Attribute, repeated: true },
  { no: 14, name: 'codes', kind: 'message', T: JobModel_Code, repeated: true },
  { no: 15, name: 'logs', kind: 'message', T: JobModel_Log, repeated: true },
])

/**
 * @generated from enum labeling.api.v1.JobModel.JobStatus
 */
export const JobModel_JobStatus = /*@__PURE__*/ proto3.makeEnum(
  'labeling.api.v1.JobModel.JobStatus',
  [
    { no: 0, name: 'new' },
    { no: 1, name: 'cancel' },
    { no: 2, name: 'labeling' },
    { no: 3, name: 'ready' },
  ]
)

/**
 * @generated from enum labeling.api.v1.JobModel.CodeStatus
 */
export const JobModel_CodeStatus = /*@__PURE__*/ proto3.makeEnum(
  'labeling.api.v1.JobModel.CodeStatus',
  [
    { no: 0, name: 'generated' },
    { no: 1, name: 'printed' },
    { no: 2, name: 'verified' },
    { no: 3, name: 'broken' },
    { no: 4, name: 'synced' },
  ]
)

/**
 * @generated from message labeling.api.v1.JobModel.Attribute
 */
export const JobModel_Attribute = /*@__PURE__*/ proto3.makeMessageType(
  'labeling.api.v1.JobModel.Attribute',
  () => [
    { no: 1, name: 'key', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 2, name: 'value', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
  ],
  { localName: 'JobModel_Attribute' }
)

/**
 * @generated from message labeling.api.v1.JobModel.Code
 */
export const JobModel_Code = /*@__PURE__*/ proto3.makeMessageType(
  'labeling.api.v1.JobModel.Code',
  () => [
    { no: 1, name: 'code', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 2, name: 'type', kind: 'scalar', T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 3, name: 'status', kind: 'enum', T: proto3.getEnumType(JobModel_CodeStatus) },
    { no: 4, name: 'parent', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 5, name: 'template', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 6, name: 'ts', kind: 'message', T: Timestamp },
  ],
  { localName: 'JobModel_Code' }
)

/**
 * @generated from message labeling.api.v1.JobModel.Log
 */
export const JobModel_Log = /*@__PURE__*/ proto3.makeMessageType(
  'labeling.api.v1.JobModel.Log',
  () => [
    { no: 1, name: 'operation', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 2, name: 'field', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 3, name: 'value', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 4, name: 'created_by', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 5, name: 'created_at', kind: 'message', T: Timestamp },
  ],
  { localName: 'JobModel_Log' }
)

/**
 * JobCreate
 *
 * @generated from message labeling.api.v1.JobCreateRequest
 */
export const JobCreateRequest = /*@__PURE__*/ proto3.makeMessageType(
  'labeling.api.v1.JobCreateRequest',
  () => [
    { no: 1, name: 'token', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 2, name: 'sign', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 3, name: 'items', kind: 'message', T: JobCreateRequest_JobCreateModel, repeated: true },
  ]
)

/**
 * @generated from message labeling.api.v1.JobCreateRequest.JobCreateModel
 */
export const JobCreateRequest_JobCreateModel = /*@__PURE__*/ proto3.makeMessageType(
  'labeling.api.v1.JobCreateRequest.JobCreateModel',
  () => [
    { no: 1, name: 'ext_id', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 2, name: 'title', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 3, name: 'total', kind: 'scalar', T: 5 /* ScalarType.INT32 */ },
    { no: 4, name: 'sku', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 5, name: 'attributes', kind: 'message', T: JobModel_Attribute, repeated: true },
  ],
  { localName: 'JobCreateRequest_JobCreateModel' }
)

/**
 * @generated from message labeling.api.v1.JobCreateResponse
 */
export const JobCreateResponse = /*@__PURE__*/ proto3.makeMessageType(
  'labeling.api.v1.JobCreateResponse',
  () => [{ no: 1, name: 'items', kind: 'message', T: JobModel, repeated: true }]
)

/**
 * JobList
 *
 * @generated from message labeling.api.v1.JobListRequest
 */
export const JobListRequest = /*@__PURE__*/ proto3.makeMessageType(
  'labeling.api.v1.JobListRequest',
  () => [
    { no: 1, name: 'token', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 2, name: 'sign', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
  ]
)

/**
 * @generated from message labeling.api.v1.JobListResponse
 */
export const JobListResponse = /*@__PURE__*/ proto3.makeMessageType(
  'labeling.api.v1.JobListResponse',
  () => [{ no: 1, name: 'items', kind: 'message', T: JobModel, repeated: true }]
)

/**
 * JobInfo
 *
 * @generated from message labeling.api.v1.JobInfoRequest
 */
export const JobInfoRequest = /*@__PURE__*/ proto3.makeMessageType(
  'labeling.api.v1.JobInfoRequest',
  () => [
    { no: 1, name: 'token', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 2, name: 'sign', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 3, name: 'uuid', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 4, name: 'extend', kind: 'scalar', T: 8 /* ScalarType.BOOL */, opt: true },
    { no: 5, name: 'offset', kind: 'message', T: Timestamp, opt: true },
    { no: 6, name: 'limit', kind: 'scalar', T: 5 /* ScalarType.INT32 */, opt: true },
  ]
)

/**
 * @generated from message labeling.api.v1.JobInfoResponse
 */
export const JobInfoResponse = /*@__PURE__*/ proto3.makeMessageType(
  'labeling.api.v1.JobInfoResponse',
  () => [
    { no: 1, name: 'data', kind: 'message', T: JobModel },
    { no: 2, name: 'total', kind: 'scalar', T: 5 /* ScalarType.INT32 */ },
  ]
)

/**
 * JobSetState
 *
 * @generated from message labeling.api.v1.JobSetStateRequest
 */
export const JobSetStateRequest = /*@__PURE__*/ proto3.makeMessageType(
  'labeling.api.v1.JobSetStateRequest',
  () => [
    { no: 1, name: 'token', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 2, name: 'sign', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 3, name: 'uuid', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 4, name: 'status', kind: 'enum', T: proto3.getEnumType(JobModel_JobStatus) },
    { no: 5, name: 'types', kind: 'scalar', T: 9 /* ScalarType.STRING */, repeated: true },
  ]
)

/**
 * @generated from message labeling.api.v1.JobSetStateResponse
 */
export const JobSetStateResponse = /*@__PURE__*/ proto3.makeMessageType(
  'labeling.api.v1.JobSetStateResponse',
  []
)

/**
 * JobCodeVerify
 *
 * @generated from message labeling.api.v1.JobCodeVerifyRequest
 */
export const JobCodeVerifyRequest = /*@__PURE__*/ proto3.makeMessageType(
  'labeling.api.v1.JobCodeVerifyRequest',
  () => [
    { no: 1, name: 'token', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 2, name: 'sign', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 3, name: 'uuid', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 4, name: 'code', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 5, name: 'type', kind: 'scalar', T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 6, name: 'status', kind: 'enum', T: proto3.getEnumType(JobModel_CodeStatus) },
  ]
)

/**
 * @generated from message labeling.api.v1.JobCodeVerifyResponse
 */
export const JobCodeVerifyResponse = /*@__PURE__*/ proto3.makeMessageType(
  'labeling.api.v1.JobCodeVerifyResponse',
  () => [{ no: 1, name: 'data', kind: 'message', T: JobModel }]
)

/**
 * JobCancel
 *
 * @generated from message labeling.api.v1.JobCancelRequest
 */
export const JobCancelRequest = /*@__PURE__*/ proto3.makeMessageType(
  'labeling.api.v1.JobCancelRequest',
  () => [
    { no: 1, name: 'token', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 2, name: 'sign', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 3, name: 'uuid', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
  ]
)

/**
 * @generated from message labeling.api.v1.JobCancelResponse
 */
export const JobCancelResponse = /*@__PURE__*/ proto3.makeMessageType(
  'labeling.api.v1.JobCancelResponse',
  []
)

/**
 * @generated from message labeling.api.v1.GetCurrentJobRequest
 */
export const GetCurrentJobRequest = /*@__PURE__*/ proto3.makeMessageType(
  'labeling.api.v1.GetCurrentJobRequest',
  []
)

/**
 * @generated from message labeling.api.v1.GetCurrentJobResponse
 */
export const GetCurrentJobResponse = /*@__PURE__*/ proto3.makeMessageType(
  'labeling.api.v1.GetCurrentJobResponse',
  () => [
    { no: 1, name: 'job_id', kind: 'scalar', T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: 'codes', kind: 'message', T: JobModel_Code, repeated: true },
  ]
)

/**
 * @generated from message labeling.api.v1.SaveCodesRequest
 */
export const SaveCodesRequest = /*@__PURE__*/ proto3.makeMessageType(
  'labeling.api.v1.SaveCodesRequest',
  () => [{ no: 1, name: 'codes', kind: 'scalar', T: 9 /* ScalarType.STRING */, repeated: true }]
)

/**
 * @generated from message labeling.api.v1.SaveCodesResponse
 */
export const SaveCodesResponse = /*@__PURE__*/ proto3.makeMessageType(
  'labeling.api.v1.SaveCodesResponse',
  () => [{ no: 1, name: 'job', kind: 'scalar', T: 9 /* ScalarType.STRING */ }]
)

/**
 * @generated from message labeling.api.v1.UpdatePrintedCodesRequest
 */
export const UpdatePrintedCodesRequest = /*@__PURE__*/ proto3.makeMessageType(
  'labeling.api.v1.UpdatePrintedCodesRequest',
  () => [
    { no: 1, name: 'codes', kind: 'message', T: UpdatePrintedCodesRequest_Code, repeated: true },
  ]
)

/**
 * @generated from message labeling.api.v1.UpdatePrintedCodesRequest.Code
 */
export const UpdatePrintedCodesRequest_Code = /*@__PURE__*/ proto3.makeMessageType(
  'labeling.api.v1.UpdatePrintedCodesRequest.Code',
  () => [
    { no: 1, name: 'code', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    { no: 2, name: 'template', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
  ],
  { localName: 'UpdatePrintedCodesRequest_Code' }
)

/**
 * @generated from message labeling.api.v1.UpdatePrintedCodesResponse
 */
export const UpdatePrintedCodesResponse = /*@__PURE__*/ proto3.makeMessageType(
  'labeling.api.v1.UpdatePrintedCodesResponse',
  () => [{ no: 1, name: 'job', kind: 'scalar', T: 9 /* ScalarType.STRING */ }]
)
