import { BarChartBottom } from './index';

/** Компонент отображает информацию о наличие/отстуствии и количестве ошибок на длине изделия. */
export default {
  component: BarChartBottom,
  argTypes: {
    codes: {
      description: 'Список кодов маркироки',
    },
    lastMeter: {
      description: 'Последний метр изделия',
    },
  },
  parameters: {
    backgrounds: {
      default: 'light',
      values: [
        { name: 'dark', value: '#242a2b' },
        { name: 'light', value: '#f4f4f4' },
        { name: 'white', value: '#fff' },
      ],
    },
  },
};
export const BarChartPrimaryGraphs1code = {
  args: {
    codes: [{ code: 3, status: 'printed' }],
    lastMeter: 1,
  },
};
export const BarChartPrimaryGraphs2code = {
  args: {
    codes: [
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
    ],
    lastMeter: 2,
  },
};
export const BarChartPrimaryGraphs3code = {
  args: {
    codes: [
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
    ],
    lastMeter: 3,
  },
};
export const BarChartPrimaryGraphs4code = {
  args: {
    codes: [
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
    ],
    lastMeter: 4,
  },
};
export const BarChartBottomPrimary = {
  args: {
    codes: [
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'broken' },
    ],
    lastMeter: 5,
  },
};
const _status = 'ok';
export const BarChartBottom18Meters = {
  args: {
    codes: [
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'broken' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
    ],
    lastMeter: 18,
  },
};

export const BarChartBottom30Meters = {
  args: {
    codes: [
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'broken' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
    ],
    lastMeter: 30,
  },
};
export const BarChartBottom50Meters = {
  args: {
    codes: [
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'broken' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
    ],
    lastMeter: 50,
  },
};
export const BarChartBottom100Meters = {
  args: {
    codes: [
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'broken' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'broken' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
    ],
    lastMeter: 100,
  },
};

export const BarChartBottom200Meters = {
  args: {
    codes: [
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'broken' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'broken' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'broken' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'broken' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
    ],
    lastMeter: 2100,
  },
};
