import BarChart from '../components/BarChart.vue'

/** Компонент отображает информацию о наличие/отстуствии и количестве ошибок на длине изделия. */
export default {
  title: 'Tablet/BarChart',
  component: BarChart,
  // tags: ["autodocs"],
  argTypes: {
    codes: {
      description: 'Список кодов маркироки',
    },
    lastMeter: {
      description: 'Последний метр изделия',
    },
  },
  parameters: {
    backgrounds: {
      default: 'light',
      values: [
        { name: 'dark', value: '#242a2b' },
        { name: 'light', value: '#f4f4f4' },
        { name: 'white', value: '#fff' },
      ],
    },
  },
}

export const BarChartPrimary = {
  args: {
    codes: [
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'broken' },
    ],
    lastMeter: 3,
  },
}
let status = 'ok'
export const BarChart18Meters = {
  args: {
    codes: [
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'broken' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
    ],
    lastMeter: 18,
  },
}

export const BarChart30Meters = {
  args: {
    codes: [
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'broken' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
    ],
    lastMeter: 30,
  },
}
export const BarChart50Meters = {
  args: {
    codes: [
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'broken' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
    ],
    lastMeter: 50,
  },
}
export const BarChart100Meters = {
  args: {
    codes: [
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'broken' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'broken' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
    ],
    lastMeter: 100,
  },
}

export const BarChart200Meters = {
  args: {
    codes: [
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'broken' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'broken' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'broken' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'broken' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
    ],
    lastMeter: 2100,
  },
}
