import type { Meta, StoryObj } from '@storybook/vue3-vite';
import { BarChart } from './index';

type Story = StoryObj<typeof BarChart>;

/** Компонент отображает информацию о наличие/отстуствии и количестве ошибок на длине изделия. */
const meta: Meta<typeof BarChart> = {
  component: BarChart,
  argTypes: {
    codes: {
      description: 'Список кодов маркироки',
    },
    lastMeter: {
      description: 'Последний метр изделия',
    },
  },
  parameters: {
    backgrounds: {
      default: 'light',
      values: [
        { name: 'dark', value: '#242a2b' },
        { name: 'light', value: '#f4f4f4' },
        { name: 'white', value: '#fff' },
      ],
    },
  },
};
export default meta;

export const BarChartPrimary: Story = {
  args: {
    codes: [
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'broken' },
    ],
    lastMeter: 3,
  },
};

export const BarChart18Meters: Story = {
  args: {
    codes: [
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'broken' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
    ],
    lastMeter: 18,
  },
};

export const BarChart30Meters: Story = {
  args: {
    codes: [
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'broken' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
    ],
    lastMeter: 30,
  },
};
export const BarChart50Meters: Story = {
  args: {
    codes: [
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'broken' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
    ],
    lastMeter: 50,
  },
};

export const BarChart100Meters: Story = {
  args: {
    codes: [
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'broken' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'broken' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
    ],
    lastMeter: 100,
  },
};

export const BarChart200Meters: Story = {
  args: {
    codes: [
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'broken' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'broken' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'broken' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'broken' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 3, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 1, status: 'printed' },
      { code: 2, status: 'printed' },
      { code: 3, status: 'printed' },
    ],
    lastMeter: 2100,
  },
};
