name: Build and Deploy Storybooks

on:
  push:
    branches: [ test/github-pages ]

permissions:
  contents: write

jobs:
  build-and-deploy-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Enable corepack and install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - run: pnpm install

      # Билды
      - run: pnpm --filter base-ui build
      - run: pnpm --filter base-ui build:storybook
      - run: pnpm --filter desktop-ui build:storybook
      - run: pnpm --filter mobile-ui build:storybook
      - run: pnpm --filter tablet-ui build:storybook
      - run: pnpm storybook build

      # Деплои (все с clean: false)
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: packages/base-ui/storybook-static
          branch: gh-pages
          target-folder: base-ui
          clean: false

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: packages/desktop-ui/storybook-static
          branch: gh-pages
          target-folder: desktop-ui
          clean: false

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: packages/mobile-ui/storybook-static
          branch: gh-pages
          target-folder: mobile-ui
          clean: false

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: packages/tablet-ui/storybook-static
          branch: gh-pages
          target-folder: tablet-ui
          clean: false

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: storybook-static
          branch: gh-pages
          clean: false