import BarChartTimeSeries from "../tablet/BarChartTimeSeries.vue";

/** Компонент отображает информацию о наличие/отстуствии ошибок на длине изделия. */
export default {
    title: "Tablet/BarChartTimeSeries",
    component: BarChartTimeSeries,
    // tags: ["autodocs"],
    argTypes: {
        codes: {
            description: 'Список кодов маркироки',
        },
           },
    parameters: {
        backgrounds: {
            default: 'light',
            values: [
                {name: 'dark', value: '#242a2b'},
                {name: 'light', value: '#f4f4f4'},
                {name: 'white', value: '#fff'},
            ]
        }
    }
};

export const BarChartTimeSeries18Meters = {
    args: {
        codes:
            [
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'broken'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'},
            ],
    },
};
export const BarChartTimeSeries25Meters = {
    args: {
        codes:
            [
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'broken'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
            ],
    },
};
export const BarChartTimeSeries30Meters = {
    args: {
        codes:
            [
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'broken'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
            ],
    },
};
export const BarChartTimeSeries60Meters = {
    args: {
        codes:
            [
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'broken'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'broken'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
            ],
    },
};
export const BarChartTimeSeries100Meters = {
    args: {
        codes:
            [
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'broken'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'broken'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
            ],
    },
};
export const BarChartTimeSeries200Meters = {
    args: {
        codes:
            [
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'broken'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'broken'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'broken'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'broken'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
            ],
    },
};
export const BarChartTimeSeries800Meters = {
    args: {
        codes:
            [
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'broken'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'broken'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'broken'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'broken'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'broken'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'broken'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
            ],
    },
};
export const BarChartTimeSeries1600Meters = {
    args: {
        codes:
            [
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'broken'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'broken'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'broken'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'broken'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'broken'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'broken'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'broken'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
                    {code: 3, status: 'printed'}, {code: 2, status: 'printed'}, {code: 1, status: 'printed'}, {code: 2, status: 'printed'}, {code: 3, status: 'printed'},
            ],
    },
};
